# Generated by Django 2.1.4 on 2018-12-10 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedid', models.CharField(max_length=700)),
                ('title', models.CharField(max_length=800)),
                ('summary', models.TextField()),
                ('destinationurl', models.CharField(max_length=800)),
                ('thumbnail', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Feedsource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=700)),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='feedsource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PiDashDisplay.Feedsource'),
        ),
    ]
