# Generated by Django 2.1.4 on 2018-12-10 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PiDashDisplay', '0003_auto_20181210_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='datecreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='feedsource',
            name='datecreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
